# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.wechatapp.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
